services:
  - type: web
    name: he-thong-ma-hoa-tinydes
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    envVars:
      - key: PORT
        value: 8000

